# Generated by Django 3.1.2 on 2020-10-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('mobile', models.IntegerField(max_length=12)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
