# Generated by Django 3.1.2 on 2020-10-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_auto_20201016_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username123', models.CharField(max_length=8)),
                ('password123', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='password123',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
